package Appointments;


/**
* Appointments/HospInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Appointments.idl
* Saturday, 26 March, 2022 4:16:36 PM EDT
*/

public interface HospInterface extends HospInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface HospInterface
